package fr.reivaxmc.progress.story;

import fr.reivaxmc.progress.ReivaxMCProgress;
import fr.reivaxmc.progress.network.ProgressNetworking;
import fr.reivaxmc.progress.network.V13Payloads;
import fr.reivaxmc.progress.progression.CampaignSavedData;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import net.minecraft.core.BlockPos;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.Heightmap;
import net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedInEvent;
import net.neoforged.neoforge.event.entity.player.PlayerInteractEvent.RightClickBlock;
import net.neoforged.neoforge.event.tick.PlayerTickEvent.Post;
import net.neoforged.neoforge.network.PacketDistributor;

/** Chapitre IV complet : témoignages, second Fragment, Concordance et première analyse. */
public final class V13Chapter4Engine {
   private static final String REWARD="CH4_MEMORY_COMPLETE",OPTIONAL_A="CH4_MARGIN_FOUND",OPTIONAL_B="CH4_CUT_FOUND";
   private static final String[] TITLES={"Le départ volontaire","L'évacuation ordonnée","La nuit sans sortie"};
   private static final String[] ACCOUNTS={
      "Nous sommes partis avant la fermeture. La Matrice a gardé la route ouverte et personne ne nous a retenus.",
      "Ils nous ont conduits vers le seuil par groupes de six. La Matrice disait que l'ordre sauverait davantage de vies.",
      "Il n'y avait plus de route. Nous avons muré les sorties nous-mêmes pour empêcher quelque chose d'entrer."
   };
   private static final String[] FRACTURES={
      "Cette version place l'aube avant l'alarme, alors que les deux autres jurent que le ciel était déjà noir.",
      "Le compte officiel nomme six survivants ; les objets conservés portent pourtant huit usages distincts.",
      "La porte décrite comme murée est la même que le premier témoignage affirme avoir franchie."
   };
   private V13Chapter4Engine(){}

   public static void onLogin(PlayerLoggedInEvent e){if(e.getEntity() instanceof ServerPlayer p){offerIfReady(p);restore(p);}}
   public static void onPlayerTick(Post e){if(!(e.getEntity() instanceof ServerPlayer p)||p.tickCount%10!=0)return;MinecraftServer s=p.getServer();if(s==null)return;offerIfReady(p);V13Chapter4Data d=V13Chapter4Data.get(s);V13Chapter4Data.Snapshot q=d.snapshot();if(q.stage().equals(V13Chapter4Rules.LOCKED)||q.stage().equals(V13Chapter4Rules.OFFERED)||q.stage().equals(V13Chapter4Rules.COMPLETE))return;
      ensureWitnesses(s);if(q.stage().equals(V13Chapter4Rules.SEEK_FRAGMENT)){ensureArchive(p.serverLevel(),CampaignSavedData.get(s),d);q=d.snapshot();if(p.blockPosition().closerThan(q.archive(),15))p.displayClientMessage(Component.literal("§3ARCHIVES BRISÉES §8• §fLa signature vient du réceptacle central. Deux marges facultatives subsistent autour de lui."),true);}
      if(q.stage().equals(V13Chapter4Rules.MATRIX_READY)&&p.blockPosition().closerThan(C110SanctuaryArchitecture.matrixThreshold(s),9))p.displayClientMessage(Component.literal("§3MATRICE §8• §fLa chambre occidentale vous reconnaît. Approchez du cœur cyan et faites CLIC DROIT."),true);
   }

   public static boolean onRightClickBlock(RightClickBlock e){if(!(e.getEntity() instanceof ServerPlayer p)||!(e.getLevel() instanceof ServerLevel))return false;MinecraftServer s=p.getServer();if(s==null)return false;V13Chapter4Data d=V13Chapter4Data.get(s);V13Chapter4Data.Snapshot q=d.snapshot();BlockPos pos=e.getPos();
      if(q.stage().equals(V13Chapter4Rules.TESTIMONIES))for(int i=0;i<3;i++)if(pos.closerThan(C110SanctuaryArchitecture.galleryWitness(s,i),2.7)){consume(e);openWitness(p,i);return true;}
      if(q.stage().equals(V13Chapter4Rules.SEEK_FRAGMENT)&&q.siteBuilt()){
         if(pos.closerThan(q.archive().offset(0,2,0),2.7)){consume(e);claimFragment(p,d);return true;}
         for(int i=0;i<2;i++)if(pos.closerThan(optionalPos(q.archive(),i),2.5)){consume(e);discoverOptional(p,d,i);return true;}
      }
      if(q.stage().equals(V13Chapter4Rules.RETURN_GALLERY)||q.stage().equals(V13Chapter4Rules.STRONG_CONCORDANCE))for(int side:new int[]{-1,1})if(pos.closerThan(C110SanctuaryArchitecture.galleryLectern(s,side),2.7)){consume(e);recoverMissingFragments(p,d);activateConcordance(p,d,side<0);return true;}
      if(pos.closerThan(C110SanctuaryArchitecture.matrixConsole(s),2.8)){
         consume(e);openMatrix(p);return true;
      }
      return false;
   }

   public static void follow(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;CampaignSavedData c=CampaignSavedData.get(s);if(!c.foundationPlaced()||!p.blockPosition().closerThan(c.foundationPos(),13)){p.displayClientMessage(Component.literal("§6PISTES §8• §fRevenez près de la Borne pour inscrire cette Piste."),false);return;}accept(p);}
   private static void accept(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;Set<String> ids=new HashSet<>();for(ServerPlayer each:s.getPlayerList().getPlayers())ids.add(each.getUUID().toString());if(ids.isEmpty())ids.add(p.getUUID().toString());V13Chapter4Data d=V13Chapter4Data.get(s);if(!d.accept(ids,p.serverLevel().getGameTime())){ProgressNetworking.openFoyerPanel(p);return;}ensureWitnesses(s);CampaignSavedData c=CampaignSavedData.get(s);c.stage("CH4_TESTIMONIES");c.addTimeline(ProgressNetworking.day(s),p.getGameProfile().getName(),V13Chapter4Rules.title(),"Trois versions d'un même événement ont été rendues lisibles dans la Galerie.");scene(s,"TROIS VOIX, UN SEUL SOUVENIR","La Galerie ouvre trois yeux. Chacun jure avoir vu la même nuit. Aucun ne se souvient du même ciel.");ProgressNetworking.syncAll(s,c);}

   private static void openWitness(ServerPlayer p,int i){String personal=personalWitness(p,i);PacketDistributor.sendToPlayer(p,new V13Payloads.OpenWitness(i,TITLES[i],ACCOUNTS[i],personal,FRACTURES[i]),new CustomPacketPayload[0]);}
   public static void acknowledgeWitness(ServerPlayer p,int i){MinecraftServer s=p.getServer();if(s==null)return;BlockPos target=C110SanctuaryArchitecture.galleryWitness(s,i);if(!p.blockPosition().closerThan(target,7)){p.displayClientMessage(Component.literal("§6GALERIE §8• §fLa version s'efface lorsque vous quittez son pupitre."),false);return;}V13Chapter4Data d=V13Chapter4Data.get(s);if(d.testimony(i,p.serverLevel().getGameTime())){F92JournalData.get(s).addPersonal(p.getUUID().toString(),"J'ai conservé « "+TITLES[i]+" ». Un détail que les autres n'ont peut-être pas perçu : "+personalWitness(p,i));p.displayClientMessage(Component.literal("§6TÉMOIGNAGE "+d.snapshot().testimonies()+"/3 §8• §fLa version est conservée sans être déclarée vraie."),false);if(d.snapshot().stage().equals(V13Chapter4Rules.SEEK_FRAGMENT)){ensureArchive(p.serverLevel(),CampaignSavedData.get(s),d);scene(s,"LA COUTURE","Les trois récits ne s'annulent pas. Ils se chevauchent comme des morceaux découpés dans des vies différentes.");}}}

   private static void claimFragment(ServerPlayer p,V13Chapter4Data d){MinecraftServer s=p.getServer();if(s==null||!d.claim(p.serverLevel().getGameTime()))return;give(p,new ItemStack((Item)ReivaxMCProgress.LAYERED_FRAGMENT.get()));CampaignSavedData c=CampaignSavedData.get(s);c.addArtifact(new CampaignSavedData.ArtifactRecord("fragment_02","Fragment stratifié",p.getGameProfile().getName(),p.getUUID().toString(),ProgressNetworking.day(s),"Archives brisées","Deux signatures superposées"));c.addTimeline(ProgressNetworking.day(s),p.getGameProfile().getName(),"Seconde signature","Un Fragment composé de couches incompatibles a été retiré des Archives brisées.");F92JournalData.get(s).addShared(ProgressNetworking.day(s),p.getGameProfile().getName(),"Le second Fragment ne contient pas un souvenir abîmé. Il contient plusieurs vies découpées puis assemblées.");p.serverLevel().sendParticles(ParticleTypes.SCULK_SOUL,p.getX(),p.getY()+1,p.getZ(),120,1.8,2,1.8,.05);p.serverLevel().playSound(null,p.blockPosition(),SoundEvents.RESPAWN_ANCHOR_CHARGE,SoundSource.BLOCKS,1.5F,.55F);scene(s,"LE FRAGMENT STRATIFIÉ","La matière se sépare en couches, puis se referme. Deux pulsations répondent depuis le même objet.");ProgressNetworking.syncAll(s,c);}

   private static void discoverOptional(ServerPlayer p,V13Chapter4Data d,int i){if(!d.optional(i)){p.displayClientMessage(Component.literal("§6MARGE §8• §fCette trace a déjà été conservée."),false);return;}MinecraftServer s=p.getServer();CampaignSavedData c=CampaignSavedData.get(s);String text=i==0?"Une phrase a été coupée au milieu : « Nous avons accepté le montage parce que la vérité entière aurait séparé les survivants. »":"Sous la dalle, deux listes utilisent les mêmes souvenirs pour désigner des personnes différentes.";String key=i==0?OPTIONAL_A:OPTIONAL_B;if(c.complete(key,18,6))F92JournalData.get(s).addShared(ProgressNetworking.day(s),p.getGameProfile().getName(),text);p.displayClientMessage(Component.literal("§6PISTE FACULTATIVE §8• §f"+text+" §8• §a+18 Âge · +6 Civilisation"),false);}

   private static void activateConcordance(ServerPlayer p,V13Chapter4Data d,boolean left){MinecraftServer s=p.getServer();if(s==null)return;if(!fragmentsNear(s)){p.displayClientMessage(Component.literal("§3CONCORDANCE §8• §fLes deux signatures doivent être présentes dans la Galerie : le Fragment inconnu et le Fragment stratifié."),false);return;}d.lectern(left,p.getUUID().toString(),p.serverLevel().getGameTime());p.serverLevel().sendParticles(ParticleTypes.ELECTRIC_SPARK,p.getX(),p.getY()+1,p.getZ(),70,1,1.4,1,.05);p.serverLevel().playSound(null,p.blockPosition(),SoundEvents.AMETHYST_BLOCK_RESONATE,SoundSource.BLOCKS,1.4F,left?.72F:1.28F);if(d.snapshot().stage().equals(V13Chapter4Rules.MATRIX_READY)){C110SanctuaryArchitecture.openMatrixChamber(s);CampaignSavedData.get(s).stage("CH4_MATRIX_READY");scene(s,"CONCORDANCE FORTE","Les deux Fragments ne fusionnent pas. Leur désaccord devient une clé, et la chambre occidentale s'ouvre.");}else p.displayClientMessage(Component.literal("§3CONCORDANCE §8• §fUn pupitre porte la première signature. Faites répondre l'autre avant que l'accord ne retombe."),false);}

   public static void openMatrix(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;V13Chapter4Data.Snapshot q=V13Chapter4Data.get(s).snapshot();V12TrailData.Snapshot previous=V12TrailData.get(s).snapshot();String policy=V13Chapter4Rules.policyConsequence(previous.policy());String heading,body,personal;boolean analyze=false,ack=false;
      if(q.stage().equals(V13Chapter4Rules.MATRIX_READY)){heading="Deux signatures en attente";body="La Matrice peut copier les signatures sans conserver les objets. Le Fragment inconnu et le Fragment stratifié vous seront immédiatement rendus, même si l'analyse échoue.";personal="Votre trace est absente de l'index actuel.";analyze=true;}
      else if(q.stage().equals(V13Chapter4Rules.REVELATION)){heading="Mémoire composite détectée";body="Les souvenirs ne sont pas seulement lacunaires. Des gestes, des peurs et des noms provenant de plusieurs vies ont été montés pour produire un récit commun cohérent. La Voix affirme : « J'ai protégé les survivants. » Le Journal ancien répond : « Elle a protégé la version qui pouvait leur survivre. »";personal=impossibleTrace(p);ack=!q.acknowledgements().contains(p.getUUID().toString());}
      else if(q.stage().equals(V13Chapter4Rules.COMPLETE)){heading="Signature impossible conservée";body="La Matrice refuse de dater cette trace. Elle porte votre empreinte, mais précède votre arrivée dans ce monde. L'origine exacte demeure verrouillée.";personal=impossibleTrace(p);}
      else {heading="Chambre silencieuse";body="La Matrice ne reconnaît pas encore une Concordance assez forte pour analyser les Fragments.";personal="Aucune lecture personnelle disponible.";}
      PacketDistributor.sendToPlayer(p,new V13Payloads.OpenMatrix(q.stage(),heading,body,personal,policy,analyze,ack),new CustomPacketPayload[0]);}

   public static void analyze(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;if(!p.blockPosition().closerThan(C110SanctuaryArchitecture.matrixConsole(s),8)){p.displayClientMessage(Component.literal("§3MATRICE §8• §fRestez près du cœur de la Matrice pendant l'analyse."),false);return;}if(!fragmentsNear(s)){p.displayClientMessage(Component.literal("§3MATRICE §8• §fLes deux Fragments doivent rester dans la chambre. Aucun ne sera consommé."),false);return;}V13Chapter4Data d=V13Chapter4Data.get(s);if(!d.analyze(p.serverLevel().getGameTime()))return;CampaignSavedData c=CampaignSavedData.get(s);c.stage("CH4_REVELATION");F92JournalData j=F92JournalData.get(s);j.addShared(ProgressNetworking.day(s),p.getGameProfile().getName(),"La Matrice a prouvé qu'une mémoire commune avait été assemblée à partir de plusieurs vies. La Voix et le Journal se contredisent sur la raison.");for(ServerPlayer each:s.getPlayerList().getPlayers())j.addPersonal(each.getUUID().toString(),impossibleTrace(each));for(ServerPlayer each:s.getPlayerList().getPlayers()){each.serverLevel().sendParticles(ParticleTypes.REVERSE_PORTAL,each.getX(),each.getY()+1,each.getZ(),100,1.3,1.8,1.3,.07);openMatrix(each);}scene(s,"LA MÉMOIRE FABRIQUÉE","Trois souvenirs se déchirent puis s'emboîtent autrement. Pendant un instant, chacun de vous apparaît dans une scène arrivée avant votre naissance.");ProgressNetworking.syncAll(s,c);}

   public static void acknowledgeRevelation(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;V13Chapter4Data d=V13Chapter4Data.get(s);if(!d.acknowledge(p.getUUID().toString(),p.serverLevel().getGameTime()))return;if(d.snapshot().stage().equals(V13Chapter4Rules.COMPLETE))complete(s,p,d);else p.displayClientMessage(Component.literal("§3MATRICE §8• §fVotre lecture est conservée. La contradiction attend encore l'autre regard."),false);}
   private static void complete(MinecraftServer s,ServerPlayer actor,V13Chapter4Data d){CampaignSavedData c=CampaignSavedData.get(s);if(d.reward()&&c.complete(REWARD,220,55)){c.addTimeline(ProgressNetworking.day(s),actor.getGameProfile().getName(),V13Chapter4Rules.title(),"Le Foyer a conservé la preuve d'une mémoire fabriquée et d'une signature impossible.");c.addArtifact(new CampaignSavedData.ArtifactRecord("trace_impossible","Signature antérieure",actor.getGameProfile().getName(),actor.getUUID().toString(),ProgressNetworking.day(s),"Matrice des Origines","Antérieure à l'arrivée des joueurs"));}c.stage("CH4_COMPLETE");scene(s,"LA MÉMOIRE N'EST PAS LA VÉRITÉ","La Matrice date votre empreinte d'avant votre arrivée. Elle ne dit pas qui l'a déposée. Pour la première fois, elle semble avoir peur de sa propre réponse.");for(ServerPlayer p:s.getPlayerList().getPlayers())p.displayClientMessage(Component.literal("§bCHAPITRE IV ACHEVÉ §8• §f+220 points d'Âge · +55 points de Civilisation · les deux Fragments restent en votre possession."),false);ProgressNetworking.syncAll(s,c);}

   private static void offerIfReady(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;V12TrailData.Snapshot before=V12TrailData.get(s).snapshot();if(!before.stage().equals(V12TrailRules.COMPLETE)||p.serverLevel().getGameTime()-before.stageTick()<1200)return;V13Chapter4Data d=V13Chapter4Data.get(s);if(d.offer(p.serverLevel().getGameTime())){CampaignSavedData c=CampaignSavedData.get(s);c.stage("CH4_OFFERED");p.displayClientMessage(Component.literal("§6NOUVELLE PISTE §8• §fLa Mémoire n'est pas la vérité §8— §7trois voix vous attendent dans la Borne."),false);ProgressNetworking.syncAll(s,c);}}
   private static void restore(ServerPlayer p){MinecraftServer s=p.getServer();if(s==null)return;V13Chapter4Data.Snapshot q=V13Chapter4Data.get(s).snapshot();if(q.stage().equals(V13Chapter4Rules.MATRIX_READY)||q.stage().equals(V13Chapter4Rules.REVELATION)||q.stage().equals(V13Chapter4Rules.COMPLETE))C110SanctuaryArchitecture.openMatrixChamber(s);if(!q.stage().equals(V13Chapter4Rules.LOCKED)&&!q.stage().equals(V13Chapter4Rules.OFFERED)&&!q.stage().equals(V13Chapter4Rules.COMPLETE))p.displayClientMessage(Component.literal("§6PISTE SUIVIE §8• §f"+V13Chapter4Rules.title()+" §8— §7"+V13Chapter4Rules.objective(q.stage(),q.testimonies(),q.acknowledgements().size())),false);}
   private static void ensureWitnesses(MinecraftServer s){ServerLevel l=s.overworld();for(int i=0;i<3;i++){BlockPos p=C110SanctuaryArchitecture.galleryWitness(s,i);l.setBlock(p.below(2),Blocks.CHISELED_DEEPSLATE.defaultBlockState(),18);l.setBlock(p.below(),Blocks.POLISHED_BLACKSTONE.defaultBlockState(),18);l.setBlock(p,((Block)ReivaxMCProgress.REGISTRY_CONSOLE.get()).defaultBlockState(),18);}}
   private static void ensureArchive(ServerLevel l,CampaignSavedData c,V13Chapter4Data d){if(d.snapshot().siteBuilt()||!c.foundationPlaced())return;BlockPos f=c.foundationPos();int x=f.getX()+286,z=f.getZ()+214,y=l.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,x,z);BlockPos a=new BlockPos(x,y,z);buildArchive(l,a);d.archive(a);c.addHistoricalSite("Archives brisées",a,l.dimension().location().toString(),"Inconnu",ProgressNetworking.day(l.getServer()));}
   private static void buildArchive(ServerLevel l,BlockPos a){Block stone=(Block)ReivaxMCProgress.SANCTUARY_STONE.get(),lumen=(Block)ReivaxMCProgress.SANCTUARY_LUMEN.get();for(int x=-12;x<=12;x++)for(int z=-12;z<=12;z++){boolean floor=Math.abs(x)<=3||Math.abs(z)<=3||Math.abs(x)==12||Math.abs(z)==12;if(floor){supportArchive(l,a.offset(x,0,z));l.setBlock(a.offset(x,0,z),(Math.floorMod(x*7+z*11,9)==0?Blocks.CRACKED_DEEPSLATE_BRICKS:Blocks.POLISHED_DEEPSLATE).defaultBlockState(),18);}for(int y=1;y<=10;y++)l.setBlock(a.offset(x,y,z),Blocks.AIR.defaultBlockState(),18);for(int y=1;y<=7;y++)if((Math.abs(x)==12||Math.abs(z)==12)&&Math.floorMod(x+z+y,5)!=0)l.setBlock(a.offset(x,y,z),stone.defaultBlockState(),18);}for(int r=2;r<=5;r++)for(int x=-r;x<=r;x++)for(int z=-r;z<=r;z++)if(Math.abs(x)+Math.abs(z)==r)l.setBlock(a.offset(x,Math.max(0,3-r),z),(r%2==0?lumen:Blocks.POLISHED_BLACKSTONE).defaultBlockState(),18);l.setBlock(a.offset(0,1,0),Blocks.CHISELED_POLISHED_BLACKSTONE.defaultBlockState(),18);l.setBlock(a.offset(0,2,0),((Block)ReivaxMCProgress.FRAGMENT_ALTAR.get()).defaultBlockState(),18);for(int i=0;i<2;i++){BlockPos p=optionalPos(a,i);supportArchive(l,new BlockPos(p.getX(),a.getY(),p.getZ()));l.setBlock(new BlockPos(p.getX(),a.getY(),p.getZ()),Blocks.POLISHED_BLACKSTONE.defaultBlockState(),18);if(p.getY()>a.getY()+1)l.setBlock(p.below(),Blocks.CHISELED_DEEPSLATE.defaultBlockState(),18);}l.setBlock(optionalPos(a,0),((Block)ReivaxMCProgress.ECHO_STONE.get()).defaultBlockState(),18);l.setBlock(optionalPos(a,1),Blocks.CHISELED_BOOKSHELF.defaultBlockState(),18);for(int x:new int[]{-8,8})for(int z:new int[]{-8,8}){supportArchive(l,a.offset(x,0,z));l.setBlock(a.offset(x,0,z),Blocks.POLISHED_BLACKSTONE.defaultBlockState(),18);for(int y=1;y<=9;y++)l.setBlock(a.offset(x,y,z),(y==6?lumen:Blocks.POLISHED_BLACKSTONE_BRICKS).defaultBlockState(),18);}}
   private static void supportArchive(ServerLevel l,BlockPos top){int ground=l.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,top.getX(),top.getZ())-1;for(int y=Math.max(l.getMinBuildHeight()+1,Math.min(ground,top.getY())-8);y<top.getY();y++)l.setBlock(new BlockPos(top.getX(),y,top.getZ()),Blocks.COBBLED_DEEPSLATE.defaultBlockState(),18);}
   private static BlockPos optionalPos(BlockPos a,int i){return i==0?a.offset(-8,2,7):a.offset(8,1,-7);}
   private static boolean fragmentsNear(MinecraftServer s){boolean first=false,second=false;BlockPos g=C110SanctuaryArchitecture.galleryLectern(s,-1);BlockPos m=C110SanctuaryArchitecture.matrixConsole(s);for(ServerPlayer p:s.getPlayerList().getPlayers())if(p.blockPosition().closerThan(g,48)||p.blockPosition().closerThan(m,18)){first|=has(p,(Item)ReivaxMCProgress.UNKNOWN_FRAGMENT.get());second|=has(p,(Item)ReivaxMCProgress.LAYERED_FRAGMENT.get());}return first&&second;}
   private static void recoverMissingFragments(ServerPlayer p,V13Chapter4Data d){MinecraftServer s=p.getServer();if(s==null)return;CampaignSavedData c=CampaignSavedData.get(s);if(c.fragmentFound()&&!globalHas(s,(Item)ReivaxMCProgress.UNKNOWN_FRAGMENT.get())){give(p,new ItemStack((Item)ReivaxMCProgress.UNKNOWN_FRAGMENT.get()));p.displayClientMessage(Component.literal("§3RELIQUAIRE §8• §fLe premier Fragment revient à son porteur."),false);}if(d.snapshot().fragmentClaimed()&&!globalHas(s,(Item)ReivaxMCProgress.LAYERED_FRAGMENT.get())){give(p,new ItemStack((Item)ReivaxMCProgress.LAYERED_FRAGMENT.get()));p.displayClientMessage(Component.literal("§3ARCHIVES §8• §fLe Fragment stratifié revient à son porteur."),false);}}
   private static boolean globalHas(MinecraftServer s,Item item){for(ServerPlayer p:s.getPlayerList().getPlayers())if(has(p,item))return true;return false;}
   private static boolean has(ServerPlayer p,Item i){return p.getInventory().contains(new ItemStack(i));}
   private static void give(ServerPlayer p,ItemStack st){if(!p.getInventory().add(st))p.drop(st,false);}
   private static String personalWitness(ServerPlayer p,int i){boolean a=(p.getUUID().getLeastSignificantBits()&1)==0;return switch(i){case 0->a?"Une main d'enfant serre un badge portant le numéro 8.":"La personne qui tient le badge a des mains adultes couvertes de cendre.";case 1->a?"La Voix prononce : « Je vous ai gardés ensemble. »":"Sous la même phrase, le Journal écrit : « Elle a surtout gardé son récit intact. »";default->a?"Dans le reflet de la porte, votre silhouette attend déjà de l'autre côté.":"Dans le reflet, la silhouette de votre partenaire arrive avant la vôtre.";};}
   private static String impossibleTrace(ServerPlayer p){return "SIGNATURE "+p.getGameProfile().getName().toUpperCase()+" · datation impossible : empreinte enregistrée avant l'arrivée du porteur.";}
   private static void scene(MinecraftServer s,String title,String text){CampaignSavedData c=CampaignSavedData.get(s);ProgressNetworking.broadcast(s,c,"CH4_"+title.hashCode(),"PISTE",title,text,0);}
   private static void consume(RightClickBlock e){e.setCanceled(true);e.setCancellationResult(InteractionResult.SUCCESS);}

   public static BlockPos currentTarget(MinecraftServer s){V13Chapter4Data.Snapshot q=V13Chapter4Data.get(s).snapshot();return switch(q.stage()){case V13Chapter4Rules.SEEK_FRAGMENT->q.archive();case V13Chapter4Rules.MATRIX_READY,V13Chapter4Rules.REVELATION->C110SanctuaryArchitecture.matrixConsole(s);default->C110SanctuaryArchitecture.galleryLectern(s,-1);};}
   public static String packet(V13Chapter4Data.Snapshot q){return q.stage()+"~"+V13Chapter4Rules.title()+"~"+V13Chapter4Rules.objective(q.stage(),q.testimonies(),q.acknowledgements().size())+"~"+q.testimonies()+"~"+q.optionals()+"~"+(q.stage().equals(V13Chapter4Rules.COMPLETE)?"1":"0");}

   public static int devCommand(ServerPlayer p,String action){MinecraftServer s=p.getServer();if(s==null)return 0;V13Chapter4Data d=V13Chapter4Data.get(s);switch(action){case"start"->{d.reset();d.offer(p.serverLevel().getGameTime());ProgressNetworking.openFoyerPanel(p);p.displayClientMessage(Component.literal("§6CHAPITRE IV DEV §8• §aPiste prête dans la Borne."),false);}case"next"->devNext(p,d);case"status"->status(p,d.snapshot());case"reset"->{d.reset();p.displayClientMessage(Component.literal("§6CHAPITRE IV DEV §8• §aRéinitialisé."),false);}default->status(p,d.snapshot());}return 1;}
   private static void devNext(ServerPlayer p,V13Chapter4Data d){MinecraftServer s=p.getServer();V13Chapter4Data.Snapshot q=d.snapshot();if(q.stage().equals(V13Chapter4Rules.OFFERED))accept(p);else if(q.stage().equals(V13Chapter4Rules.TESTIMONIES)){for(int i=0;i<3;i++)d.testimony(i,p.serverLevel().getGameTime());ensureArchive(p.serverLevel(),CampaignSavedData.get(s),d);}else if(q.stage().equals(V13Chapter4Rules.SEEK_FRAGMENT)){ensureArchive(p.serverLevel(),CampaignSavedData.get(s),d);if(d.claim(p.serverLevel().getGameTime()))give(p,new ItemStack((Item)ReivaxMCProgress.LAYERED_FRAGMENT.get()));}else if(q.stage().equals(V13Chapter4Rules.RETURN_GALLERY)||q.stage().equals(V13Chapter4Rules.STRONG_CONCORDANCE)){List<String> ids=new ArrayList<>(q.participants());String a=ids.isEmpty()?p.getUUID().toString():ids.get(0),b=ids.size()>1?ids.get(1):a;d.lectern(true,a,p.serverLevel().getGameTime());d.lectern(false,b,p.serverLevel().getGameTime()+1);C110SanctuaryArchitecture.openMatrixChamber(s);}else if(q.stage().equals(V13Chapter4Rules.MATRIX_READY)){if(!has(p,(Item)ReivaxMCProgress.UNKNOWN_FRAGMENT.get()))give(p,new ItemStack((Item)ReivaxMCProgress.UNKNOWN_FRAGMENT.get()));if(!has(p,(Item)ReivaxMCProgress.LAYERED_FRAGMENT.get()))give(p,new ItemStack((Item)ReivaxMCProgress.LAYERED_FRAGMENT.get()));d.analyze(p.serverLevel().getGameTime());}else if(q.stage().equals(V13Chapter4Rules.REVELATION)){for(String id:q.participants())d.acknowledge(id,p.serverLevel().getGameTime());if(d.snapshot().stage().equals(V13Chapter4Rules.COMPLETE))complete(s,p,d);}status(p,d.snapshot());}
   private static void status(ServerPlayer p,V13Chapter4Data.Snapshot q){p.displayClientMessage(Component.literal("§6CHAPITRE IV §8• §f"+q.stage()+" §8• §fTémoignages "+q.testimonies()+"/3 · Marges "+q.optionals()+"/2 · Lectures "+q.acknowledgements().size()+"/"+q.participants().size()),false);}
}
